M48
; DRILL file {KiCad 9.0.1} date 2025-05-28T15:06:31+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-28T15:06:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X131.98Y-81.6
X138.0Y-81.6
T2
X127.5Y-78.6
X142.0Y-78.6
M30
